direction: down

Strategic: Strategic Layer: {
  Governance: |md
    # Governance and Posture
    - Govern AI agents like individuals
    - establish trusted digital identity
    - increase ISMS cadendece
    - Watch shadow AI
  |
  Architecture: |md
    # Architecture and Design
    - Least priviledge for Individuals and AI Agents
    - Automatic revocation
    - defensive prompt layer
    - increase ISMS cadende
  |
}

Operational: Operational Layer: {
  Monitoring: |md
    # Monitoring and Detection
    - automatted detection
    - monitor LLM queries
    - verify individuals
  |
  Response: |md
    # Response and Recovery
    - Automated remediation
    - AI break glass procedures
    - Supply chain severing plans
  |
}

Strategic -> Operational: {
  style: {
    stroke-width: 0
  }
}
